### ISSUE TITLE
Yahoo finance not supported

### ISSUE THREAD

**Issue by Dawny33** [davidastephens/pandas-finance#6]
Looks like `pandas-datareader` has deprecated support for Yahoo finance. The corresponding error trace:

```
Traceback (most recent call last):
  File "api.py", line 228, in <module>
    aapl.options
  File "api.py", line 34, in options
    return OptionChain(self)
  File "api.py", line 188, in __init__
    self._pdr = pdr.Options(self.underlying.ticker, 'yahoo', session=self._session)
  File "/path/to/repo/pandas-finance/venv/lib/python3.7/site-packages/pandas_datareader/data.py", line 467, in Options
    raise ImmediateDeprecationError(DEP_ERROR_MSG.format('Yahoo Options'))
pandas_datareader.exceptions.ImmediateDeprecationError:
Yahoo Options has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

See https://github.com/pydata/pandas-datareader/issues
```

Any other finance APIs suggested?

**Comment by davidastephens** [comment]
I have not seen another source for options data unfortunately.

**Comment by Dawny33** [comment]
Yeah. Yahoo API's change has been a leftpad moment for data folks.

Anyways, you might find these resources interesting: https://news.ycombinator.com/item?id=14091952
